stages:
  - test
  - build
  - deploy

cache:
  paths:
  - node_modules/

test:
  stage: test
  image: node:7
  script:
    - npm install --silent
    - npm run test
build:
  stage: build
  image: node:7
  script:
    - npm install --silent
    - npm run build
  artifacts:
    paths:
      - lib
pages:
  stage: deploy
  image: node:7
  script:
    - npm install --silent
    - npm run build-storybook -- -o public
  artifacts:
      paths:
        - public
  dependencies:
    - build
  only:
    - master
